# Collaborators (including web sites where you got help: (enter none if you didn't need help)
#  none
print("Hello welcome to madlibs! You ready?")
input()
print("Great lets get started!")
adjective = input("type an adjective ")
nationality = input("type a nationality ")
person = input("type a person ")
noun = input ("type a noun ")
adjective2 = input("type  an adjective ")
noun2 = input("type a noun ")
adjective3 = input("type an adjective ")
adjective4 = input("type an adjective ")
plural_noun = input("type a plural noun ")
noun3 = input("type a noun ")
number = input("type a number ")
shapes = input("type a shape ")
food = input("type a food ")
food2 = input("type a food ")
number2 = input("type a number ")
print("Pizza was invented by " + adjective + " " + nationality + " chef named " + person + ".")
print(" To make a pizza, you need to take a lump of " + noun + ", and make a thin, round " + adjective2 + " " + noun2 + ".")
print(" Then you cover it with " + adjective3 + " sauce, " + adjective4 + " cheese, and fresh chopped " + plural_noun + ".")
print(" Next you have to bake it in a very hot " + noun3 + ". When it is done, cut it into " + number + " " + shapes)
print(" Some kids like " + food + " pizza the best, but my favorite is the " + food2 + " pizza.")
print(" If i could, I would eat pizza " + number2 + " times a day!")